---
title: "Preliminaries in R"
author: "Brooke Anderson, Assistant Professor of Epidemiology"
job: Colorado State University
logo        : CSU_ram.png
date: "August 24, 2015"
output: ioslides_presentation
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
mode        : selfcontained # {standalone, draft}
---

## What is R?

- A statistical programming language
- Open-source
- A core package with many available user-created add-ons (packages)

## What is R?

Currently popular in a number of fields, including:

- Statistics
- Machine learning
- Data journalism / Data analysis

## What is R?

"The best thing about R is that it was developed by statisticians. The worst thing about R is that... it was developed by statisticians.

-Bo Cowgill, Google, at the Bay Area R Users Group

## Gratis vs. libre

- Gratis: Free as in beer
- Libre: Free as in speech

With open-source software (free as in speech), you can:

- Check out the code to figure out how the software works
- Share the code (and software) with other people
- Make any changes you want to the code

## What is RStudio?

RStudio is a user interface for R. You download it separately, but it's a "nicer" way to work in R. 

RStudio (the company) currently:

- Develops and freely provides the RStudio IDE
- Provides excellent resources for learning and using R (cheatsheets, )
- Is producing some of the most-used R packages
- Employees some of the top people in R development

## Setting up

If do not already have them, you will need to download and install both R and RStudio. 

- Go to [CRAN](https://cran.r-project.org) and download the latest version of R for your system. Install.
- Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/) and download the latest version of RStudio for your system. Install. 
- Defaults should be fine for everything.
